apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-grafana
spec:
  rules:
   host: grafana.test
   http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: loki-grafana
            port:
              number: 80
