apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: loki-stack
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: grafana.test.geschool.id
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: loki-stack-1633489134-grafana
            port:
              number: 80
