apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: promse-ing
  namespace: loki-stack
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: ps.test.geschool.id
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: loki-stack-1633489134-prometheus-server
            port:
              number: 80
