apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    tier: web
data:
  config : |
    server {
      listen 80 default_server;
      add_header X-Node    $hostname;
      client_max_body_size 100M;
      
      root /var/www/html;

      server_tokens off;

      gzip             on;
      gzip_min_length  1000;
      gzip_proxied     any;
      gzip_types       text/plain application/xml text/css application/x-javascript text/javascript application/octet-stream;


      location / {
        try_files $uri /index.php?$args;
      }

     location /publics/ {
        try_files $uri =404;
      }

      location ~ /protected/ {
        return 404;
      }
    
      location ~ ^/.*.php {
        fastcgi_split_path_info  ^(.+\.php)(.*)$;
        include fastcgi_params;
        fastcgi_read_timeout 150s;
        fastcgi_param  SCRIPT_FILENAME  /var/www/html/$fastcgi_script_name;
        fastcgi_param  PATH_INFO        $fastcgi_path_info;
        fastcgi_param  PATH_TRANSLATED  /var/www/html/$fastcgi_script_name;
        fastcgi_pass 127.0.0.1:9000;

      }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fpm-config
  labels:
    tier: web
data:
  config : |
    [global]

    error_log = log/error.log
    log_level = notice

    [www]

      clear_env = no
      user = daemon
      group = daemon

      listen = 9000

      listen.backlog = 1024

      pm = static

      pm.max_children = 50

      pm.start_servers = 20

      pm.min_spare_servers = 10

      pm.max_spare_servers = 20

      pm.max_requests = 100

      pm.status_path = /status-fpm.php

      include=/opt/bitnami/php/etc/environment.conf
      include=/opt/bitnami/php/etc/common.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  labels:
    tier: web
data:
  config : |
    [INPUT]
      Name        tail
      Path        /var/www/html/tmp/log_tryout_*.txt
      DB          /var/www/html/tmp/fluentbit.db

    [OUTPUT]
      Name    http
      Match   *
      Format  json_lines
      Host    10.130.226.136
      Port    80
      URI     /_api/log/digest?sender=${GS_APP_NAME}    
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    tier: web
    monitoring: "fpm"
spec:
  selector:
    app: web
    tier: web
  ports:
  - name: web 
    protocol: TCP
    port: 80
    targetPort: 80
  - name: php
    protocol: TCP
    port: 9000
    targetPort: 9000
  - name: fpm-metric
    port: 9253
    targetPort: 9253
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    tier: web
    exporter: "fpm"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      tier: web
  template:
    metadata:
      labels:
        app: web
        tier: web
    spec:
      volumes:
      - name: app-staging
        nfs:
          server: 10.130.226.136
          path: /
      - name: app-tmp
        emptyDir: {}
      - name: app-runtime
        emptyDir: {}
      - name: fpm-config
        configMap:
          name: fpm-config
          items:
          - key: config
            path: www.conf      
      - name: fluentbit-config
        configMap:
          name: fluentbit-config
          items:
          - key: config
            path: fluent-bit.conf
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
          - key: config
            path: default.conf
      containers:
      - name: nginx
        image: registry.digitalocean.com/geschool/nginx-php:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        resources:
          requests:
            cpu: "10m"
      - name : php
        image: registry.digitalocean.com/geschool/php:latest
        resources:
          requests:
            cpu: "100m"
        livenessProbe:
          exec:
            command:
              - "/fpm-check.sh"
          initialDelaySeconds: 5
          failureThreshold: 2

        env:
          - name: GS_APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
        - name: app-staging
          mountPath: /var/www/html/protected/runtime/staging/
        - name: app-tmp
          mountPath: /var/www/html/tmp
        - name: app-runtime
          mountPath: /var/www/html/protected/runtime
        - name: fpm-config
          mountPath: /opt/bitnami/php/etc/php-fpm.d
      - name: fluentbit
        image: bitnami/fluent-bit:latest
        resources:
          requests:
            cpu: "10m"
          limits:
            cpu: "50m"
        volumeMounts:
        - name: app-tmp
          mountPath: /var/www/html/tmp
        - name: fluentbit-config
          mountPath: /opt/bitnami/fluent-bit/conf/
        env:
          - name: GS_APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace  
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: web
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: web
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
